<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
</body>
<script>
    let p =new Promise((resolve,reject)=>{
         resolve('sucess')
        // reject('fault')

    })
    
  const result=p.then(value=>{
        console.log(111)
        //有且只有一个方式能中断promise链:返回 pending姿态的promise对象，
        //因为只有改变状态才会执行then方法定义的回调函数
        //如果调用返回reject状态的promise对象则会直接调用catch中定义的回调
        return new Promise((resolve,reject)=>{reject()})
    }).then(value=>{
        console.log(222)
    }).then(value=>{
        console.log(333)
    }).catch(reason=>{
        console.warn(reason)
    })
console.log(result)
</script>
</html>